package com.mindfulai.customclass;

import java.util.ArrayList;
import java.util.Arrays;

public class CityData {
    private ArrayList<String> city = new ArrayList<>();
    private ArrayList<String> state = new ArrayList<>();
    private String[] allcity = {
            "Mumbai",
            "Delhi",
            "Bangalore",
            "Hyderabad",
            "Ahmedabad",
            "Chennai",
            "Kolkata",
            "Surat",
            "Pune",
            "Jaipur",
            "Lucknow",
            "Kanpur",
            "Nagpur",
            "Indore",
            "Port Blair",
            "Leh",
            "Kavaratti",
            "Pondicherry",
            "Thane",
            "Bhopal",
            "Visakhapatnam",
            "Pimpri-Chinchwad",
            "Patna",
            "Vadodara",
            "Ghaziabad",
            "Ludhiana",
            "Agra",
            "Nashik",
            "Faridabad",
            "Meerut",
            "Rajkot",
            "Kalyan-Dombivli",
            "Vasai-Virar",
            "Varanasi",
            "Srinagar",
            "Aurangabad",
            "Dhanbad",
            "Amritsar",
            "Navi Mumbai",
            "Allahabad",
            "Howrah",
            "Ranchi",
            "Gwalior",
            "Jabalpur",
            "Coimbatore",
            "Vijayawada",
            "Jodhpur",
            "Madurai",
            "Raipur",
            "Kota[6]",
            "Chandigarh",
            "Guwahati",
            "Solapur",
            "Hubli–Dharwad",
            "Tiruchirappalli[7]",
            "Bareilly",
            "Mysore",
            "Tiruppur",
            "Gurgaon",
            "Aligarh",
            "Jalandhar",
            "Bhubaneswar",
            "Salem",
            "Mira-Bhayandar",
            "Warangal[8]",
            "Jalgaon",
            "Guntur[9]",
            "Bhiwandi",
            "Saharanpur",
            "Gorakhpur",
            "Bikaner",
            "Amravati",
            "Noida",
            "Jamshedpur",
            "Bhilai",
            "Cuttack",
            "Firozabad",
            "Kochi",
            "Nellore",
            "Bhavnagar",
            "Dehradun",
            "Durgapur",
            "Asansol",
            "Rourkela",
            "Nanded",
            "Kolhapur",
            "Ajmer",
            "Akola",
            "Gulbarga",
            "Jamnagar",
            "Ujjain",
            "Loni",
            "Siliguri",
            "Jhansi",
            "Ulhasnagar",
            "Jammu",
            "Sangli-Miraj & Kupwad",
            "Mangalore",
            "Erode",
            "Belgaum",
            "Ambattur",
            "Tirunelveli",
            "Malegaon",
            "Gaya",
            "Thiruvananthapuram",
            "Udaipur",
            "Maheshtala",
            "Davanagere",
            "Kozhikode",
            "Kurnool",
            "Rajpur Sonarpur",
            "Rajahmundry",
            "Bokaro",
            "South Dumdum",
            "Bellary",
            "Patiala",
            "Gopalpur",
            "Agartala",
            "Bhagalpur",
            "Muzaffarnagar",
            "Bhatpara",
            "Panihati",
            "Latur",
            "Dhule",
            "Tirupati[16]",
            "Rohtak",
            "Korba",
            "Bhilwara",
            "Berhampur",
            "Muzaffarpur",
            "Ahmednagar",
            "Mathura",
            "Kollam",
            "Avadi",
            "Kadapa",
            "Kamarhati",
            "Sambalpur",
            "Bilaspur",
            "Shahjahanpur",
            "Satara",
            "Bijapur",
            "Kakinada",
            "Rampur",
            "Shimoga",
            "Chandrapur",
            "Junagadh",
            "Thrissur",
            "Alwar",
            "Bardhaman",
            "Kulti",
            "Nizamabad",
            "Parbhani",
            "Tumkur",
            "Khammam",
            "Ozhukarai",
            "Bihar Sharif",
            "Panipat",
            "Darbhanga",
            "Bally",
            "Aizawl",
            "Dewas",
            "Ichalkaranji",
            "Karnal",
            "Bathinda",
            "Jalna",
            "Eluru[17]",
            "Barasat",
            "Kirari Suleman Nagar",
            "Purnia[18]",
            "Satna",
            "Mau",
            "Sonipat",
            "Farrukhabad",
            "Sagar",
            "Durg",
            "Imphal",
            "Ratlam",
            "Hapur",
            "Arrah",
            "Anantapur",
            "Karimnagar",
            "Etawah",
            "Ambarnath",
            "North Dumdum",
            "Bharatpur",
            "Begusarai",
            "New Delhi",
            "Gandhidham",
            "Baranagar",
            "Tiruvottiyur",
            "Pondicherry",
            "Sikar",
            "Thoothukudi",
            "Rewa",
            "Mirzapur",
            "Raichur",
            "Pali",
            "Ramagundam[19]",
            "Haridwar",
            "Vijayanagaram",
            "Katihar",
            "Nagercoil",
            "Sri Ganganagar",
            "Karawal Nagar",
            "Mango",
            "Thanjavur",
            "Bulandshahr",
            "Uluberia",
            "Katni",
            "Sambhal",
            "Singrauli",
            "Nadiad",
            "Secunderabad",
            "Naihati",
            "Yamunanagar",
            "Bidhannagar",
            "Pallavaram",
            "Bidar",
            "Munger",
            "Panchkula",
            "Burhanpur",
            "Raurkela Industrial Township",
            "Kharagpur",
            "Dindigul",
            "Gandhinagar",
            "Hospet",
            "Nangloi Jat",
            "Malda",
            "Ongole",
            "Deoghar",
            "Chapra",
            "Haldia",
            "Khandwa",
            "Nandyal",
            "Morena",
            "Amroha",
            "Anand",
            "Bhind",
            "Bhalswa Jahangir Pur",
            "Madhyamgram",
            "Bhiwani",
            "Berhampore",
            "Ambala",
            "Morbi",
            "Fatehpur",
            "Raebareli",
            "Mahaboobnagar",
            "Chittoor[20]",
            "Bhusawal",
            "Orai",
            "Bahraich",
            "Vellore",
            "Mehsana",
            "Raiganj",
            "Sirsa",
            "Danapur",
            "Serampore",
            "Sultan Pur Majra",
            "Guna",
            "Jaunpur",
            "Panvel",
            "Shivpuri",
            "Surendranagar Dudhrej",
            "Unnao",
            "Chinsurah",
            "Alappuzha",
            "Kottayam",
            "Machilipatnam",
            "Shimla",
            "Adoni",
            "Udupi",
            "Tenali",
            "Proddatur",
            "Saharsa",
            "Hindupur",
            "Sasaram",
            "Hajipur[23]",
            "Bhimavaram",
            "Kumbakonam",
            "Dehri[22]",
            "Madanapalle",
            "Siwan[24]",
            "Bettiah[25]",
            "Guntakal",
            "Srikakulam",
            "Motihari[26]",
            "Dharmavaram",
            "Gudivada",
            "Phagwara",
            "Narasaraopet",
            "Suryapet",
            "Miryalaguda",
            "Tadipatri",
            "Karaikudi",
            "Kishanganj[27]",
            "Jamalpur[28]",
            "Kavali",
            "Tadepalligudem",
            "Amaravati",
            "Buxar",
            "Jehanabad",
            "Aurangabad",
            "Gangtok",
    };

    public ArrayList<String> getCity() {
        city.addAll(Arrays.asList(allcity).subList(0, 299));
        return city;
    }

    public ArrayList<String> getState() {
        state.add("State");
        state.add("Uttar Pradesh");
        state.add("Andaman and Nicobar Islands");
        state.add("Chandigarh");
        state.add("Dadra and Nagar Haveli");
        state.add("Daman and Diu");
        state.add("Delhi");
        state.add("Jammu and Kashmir");
        state.add("Ladakh");
        state.add("Lakshadweep");
        state.add("Puducherry");
        state.add("Andhra Pradesh");
        state.add("Arunachal Pradesh");
        state.add("Assam");
        state.add("Bihar");
        state.add("Chhattisgarh");
        state.add("Goa");
        state.add("Gujarat");
        state.add("Haryana");
        state.add("Himachal Pradesh");
        state.add("Jammu and Kashmir");
        state.add("Jharkhand");
        state.add("Karnataka");
        state.add("Kerala");
        state.add("Madhya Pradesh");
        state.add("Maharashtra");
        state.add("Manipur");
        state.add("Meghalaya");
        state.add("Mizoram");
        state.add("Nagaland");
        state.add("Odisha");
        state.add("Punjab");
        state.add("Rajasthan");
        state.add("Sikkim");
        state.add("Tamil Nadu");
        state.add("Telangana");
        state.add("Tripura");
        state.add("Uttarakhand");
        state.add("West Bengal");
        return state;
    }
}
